version: '3.8'
services:
  rest-api:
    image: rest-api:1.0.0
    container_name: rest-api
    ports:
    - 4000:4000
    
  mongo:
    ports:
    - '27017:27017'
    container_name: mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongo
    - MONGO_INITDB_ROOT_PASSWORD=12345
    image: mongo
    volumes:
    - data:/data


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: 12345
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongo://mongo:12345@192.168.102.52:27017/
    depends_on:
      - mongo
volumes:
  data:
