apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespcace: rest
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    apps: api
