apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: rest
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      apps: api
  template:
    metadata:
      labels:
        apps: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: connection-string
                key: url
