apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
  namespcace: rest
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort:  {{ .Values.mongo.service.port }}
      protocol: 'TCP'
  selector:
    apps: mongo
