apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongo-data
  namespace: rest
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo-data
    namespace: rest
  hostPath:
    path: {{ .Values.mongo.PersistentVolume.path }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem