apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-data
  name: mongo-data
  namespace: rest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: mongo-data
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi